# Generated by Django 4.1.2 on 2022-10-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
